version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - '3316:3306' # ホストからゲストへポートフォワード
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: abi
      MYSQL_PASSWORD: abi
      MYSQL_DATABASE: abi
  test-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: 'abi'
      MYSQL_PASSWORD: 'abi'
      MYSQL_DATABASE: test_abi
    ports:
      - '3307:3306' # ローカルPCから接続するために設定
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true 
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
      - chrome
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/myproject # ソースコード変更したらDocker側も即反映されるように

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444